version: '3'
services:
  eureka:
    image: linuxautomations/ms-eureka-server
    ports:
      - "8761:8761"
  customer:
    image: linuxautomations/ms-customer
    links:
     - eureka
  catalog:
    image: linuxautomations/ms-catalog
    links:
     - eureka
  order:
    image: linuxautomations/ms-order
    links:
     - eureka
  zuul:
    image: linuxautomations/ms-zuul-server
    links:
     - eureka
    ports:
      - "8080:8080"
  turbine:
    image: linuxautomations/ms-turbine-server
    links:
     - eureka
    ports:
      - "8989:8989"


