apiVersion: v1
kind: Pod
metadata:
  name: eureka
spec:
  containers:
    - name: eureka
      image: linuxautomations/ms-eureka-server
      ports:
        - containerPort: 8761
    - name: customer
      image: linuxautomations/ms-customer


